[mypy]
python_version = 3.11
check_untyped_defs = true
ignore_missing_imports = true
show_column_numbers = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true

[mypy-commons.pagination]
ignore_errors = true

[mypy-commons.apispec]
ignore_errors = true

[mypy-services.open_ai]
ignore_errors = true
