"""autogenerate

Revision ID: 4072516fc26f
Revises:
Create Date: 2025-06-12 17:56:19.418402

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4072516fc26f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poster_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('text_subtitle', sa.String(length=100), nullable=False),
    sa.Column('reward_amount', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rendered_image_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poster_requests')
    # ### end Alembic commands ###
